/*
 * This source file was generated by the Gradle 'init' task
 */
package cordinateswebsiteplugin;

import java.lang.reflect.AccessFlag.Location;

import org.bukkit.plugin.java.JavaPlugin;
import org.bucket.event.EventHandler;
import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.entity.player;

public class Main extends JavaPlugin {
    @Override
    public void onEnable() {
        // Plugin startup logic
    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic

    @EventHandler
    public void onPlayerMove(PlayerMoveEvent event) {
        player player = event.getPlayer();
        location location = player.getlocation();
        double x = Location.getX();
        double y = Location.getY();
        double z = Location.getZ();

    }
}
